server:
  port: 8081
eureka:
 client:
  serviceUrl:
   defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  healthcheck:
    enabled: true

 instance:
  lease-expiration-duration-in-seconds: 90
  statusPageUrlPath: /actuator/info
  healthCheckUrlPath: /actuator/health

spring:
 redis:
   host: 192.168.99.100
   port: 6379
   connection:
     time-out-sec: 1
     read-time-out-sec: 1